- name: printing variables
  hosts: web
  vars:
    num1: 10
  become: yes
  tasks:
    - name: printing variable
      ansible.builtin.debug:
        msg: "hi {{ num1}} is greater than 5"
      when: num1<5  
