---
- name: adding user
  hosts: web
  become: yes
  tasks:
    - name: install nginx if it is redhat
      ansible.builtin.dnf
        name: nginx
        state: present
      when: ansible_os_family="REDHAT"   

    - name: print user details
      ansible.builtin.debug:
        msg: "{{ user }}"
