---
- name: adding user
  hosts: web
  become: yes
  tasks:
    - name: install nginx if it is redhat
      ansible.builtin.dnf
        name: nginx
        state: present
      when: ansible_facts.os_family == "RedHat"

