


- name: printing variables
  hosts: web
  vars_prompt:
    - name: "name1"           # Define the variable name as "name1"
      prompt: "Enter name1"    # The prompt message shown to the user
  become: yes
  tasks:
    - name: printing variable
      ansible.builtin.debug:
        msg: "hi {{ name1 }}"   # Print the value of the variable "name1"
       
