- name: loops
  hosts: web
  become: yes
  tasks:
   - name: configuring names
     ansible.builtin.debug:
       msg: "{{ansible_facts}}"

   - name: ansible to install pacakges
     ansible.builtin.dnf:
       name: nginx
       state: present
     when: ansible_os_family="RedHat"
