- name: loops
  hosts: web
  become: yes
  tasks:
   - name: configuring names
     ansible.builtin.debug:
       msg: "{{ansible_facts}}"

   - name: ansible to install pacakage 
     ansible.builtin.dnf:
       name: nginx
       state: present
     when: ansible_os_family=="RedHat"

   - name: ansible to install  package in ubuntu
   ansible.builtin.apt:
     name: docker
     state: present
   when: ansible_os_family=="ubuntu"  
