
- name: installing nginx server
  hosts: web
  become: yes
  tasks:
    - name: installing nginx server
      ansible.builtin.package:
        name: nginx
        state: present
        

    - name: starting nginx service
      ansible.builtin.service:
        name: nginx
        state: started
