---
- name: adding user
  hosts: web
  become: yes
  tasks:
    - name: check if user "expense" exists
      ansible.builtin.command: id expense
      register: user
      ignore_errors: yes

    - name: print user details
      ansible.builtin.debug:
        msg: "{{ user }}"
