


- name: printing variables
  hosts: web
  vars_files:
   - nav.yml
  
  become: yes
  tasks:
    - name: printing variable
      ansible.builtin.debug:
        msg: "hi {{ course }}"   # Print the value of the variable "name1"
       
