- name: debug module
  hosts: web
  vars_files:
   - vars.yml

  vars_prompt:
    name: "course"
    prompt: "please enter course name" 
    
  become: yes
  tasks:
   - name: installing
     ansible.builtin.debug:
       msg: "hi {{course}}"



