- name: printing variables
  hosts: web
  vars_prompt:
    - name1: naveen
      msg: "enter name1"
  become: yes
  tasks:
    - name: printing variable
      ansible.builtin.debug:
        msg: "hi {{ name1 }}"
