- name: printing variables
  hosts: web
  become: yes
  tasks:
   - name: checking wheater user exists or not
     ansible.builtin.command: id expense
     register: user
     ignore_errors: yes

   - name: printing user info
     ansible.builtin.debug:
       msg: "{{user}}"
       
   - name: adding user
     ansible.builtin.command: useradd expense
     when: user.rc!=0

