- name: installing nginx
  hosts: web
  become: yes
  tasks:
   - name: installing nginx server
     ansible.builtin.package:
        name: nginx
        state: present  
   - name: starting service
     ansible.builtin.service:
       name: nginx
       state: started             